export default {
  content: ["dist/**/*.html"],
  css: ["dist/css/styles.css", "dist/css/styles.min.css"],
  safelist: [
    /^navbar/,
    /^nav-/,
    /^collapse/,
    /^show$/,
    /^container/,
    /^row$/,
    /^col/,
    /^px-/,
    /^py-/,
    /^mx-/,
    /^my-/,
    /^ms-/,
    /^me-/,
    /^d-/,
    /^text-/,
    /^align-/,
    /^justify-/,
    /^list-/,
    /^btn/,
    /^icon/,
    /^tweet/,
    /^react-tweet/,
    /^lite/
  ],
};
